### ISSUE TITLE
Send back model JSON diff

### ISSUE THREAD

**Issue by activey** [activey/licket#28]
When component is updated at server side, then whole component object is sent back and model is replaced in JS. It would be nice if only updated part of model would be returned back. Consider two libraries, at JS level: https://github.com/Starcounter-Jack/JSON-Patch, and on Java level: https://github.com/flipkart-incubator/zjsonpatch

**Comment by warpech** [comment]
JSON-Patch is also used in a more sophisticated library https://github.com/palindrom/palindrom that sends JSON-Patches over HTTP Patch and WebSocket with Operational Transformation. Maybe worth having a look?

**Comment by activey** [comment]
Already did, palindrom does a little bit too much for this purpose and it's little bit too generic, I have slightly different situation here but thanks ;)

**Comment by activey** [comment]
Done.
