### ISSUE TITLE
Refactor those two properties for storing elements and attributes, could be aggregated/wrapped with something smarter

### ISSUE THREAD

**Issue by activey** [activey/licket#4]

**Comment by dejan2609** [comment]
:cool: project !
@activey: let me know in case you need some/any kind of help with maven, I will try help you as much as I could :smile:

**Comment by activey** [comment]
Hi @dejan2609 :) Sure! I appreciate any kind of help :) Please not this is still very veeery experimental ;) No tests at all ;P (had to spit it out of my head at once). Just for me and create pull request :)

**Comment by activey** [comment]
Damn, I don't remember what what this task about :D

**Comment by activey** [comment]
No idea what was this about, closing.
